// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx/esm prisma/seed.ts",
  },
  datasource: {
    // TODO: 将来的に src/env.ts（Zod）で DATABASE_URL を検証・型付けする予定
    // 現時点では undefined の場合に実行時クラッシュを防ぐため非 null アサーションを使用する
    url: process.env["DATABASE_URL"]!,
  },
});
