// 追加 (#120): メールアドレス確認関連の定数
export const EMAIL_VERIFICATION_TOKEN_TTL_HOURS = 24
export const EMAIL_VERIFICATION_TOKEN_TTL_MS =
  EMAIL_VERIFICATION_TOKEN_TTL_HOURS * 60 * 60 * 1000
export const EMAIL_VERIFICATION_TOKEN_BYTES = 32
